// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               unknown
// source: ibc/applications/transfer/v1/transfer.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
export const protobufPackage = "ibc.applications.transfer.v1";
function createBaseParams() {
    return { sendEnabled: false, receiveEnabled: false };
}
export const Params = {
    encode(message, writer = new BinaryWriter()) {
        if (message.sendEnabled !== false) {
            writer.uint32(8).bool(message.sendEnabled);
        }
        if (message.receiveEnabled !== false) {
            writer.uint32(16).bool(message.receiveEnabled);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseParams();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.sendEnabled = reader.bool();
                    continue;
                }
                case 2: {
                    if (tag !== 16) {
                        break;
                    }
                    message.receiveEnabled = reader.bool();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            sendEnabled: isSet(object.sendEnabled) ? globalThis.Boolean(object.sendEnabled) : false,
            receiveEnabled: isSet(object.receiveEnabled) ? globalThis.Boolean(object.receiveEnabled) : false,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.sendEnabled !== false) {
            obj.sendEnabled = message.sendEnabled;
        }
        if (message.receiveEnabled !== false) {
            obj.receiveEnabled = message.receiveEnabled;
        }
        return obj;
    },
    create(base) {
        return Params.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseParams();
        message.sendEnabled = object.sendEnabled ?? false;
        message.receiveEnabled = object.receiveEnabled ?? false;
        return message;
    },
};
function isSet(value) {
    return value !== null && value !== undefined;
}
