// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               unknown
// source: cosmos/group/v1/events.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import Long from "long";
import { proposalExecutorResultFromJSON, proposalExecutorResultToJSON, proposalStatusFromJSON, proposalStatusToJSON, TallyResult, } from "./types";
export const protobufPackage = "cosmos.group.v1";
function createBaseEventCreateGroup() {
    return { groupId: Long.UZERO };
}
export const EventCreateGroup = {
    encode(message, writer = new BinaryWriter()) {
        if (!message.groupId.equals(Long.UZERO)) {
            writer.uint32(8).uint64(message.groupId.toString());
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseEventCreateGroup();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.groupId = Long.fromString(reader.uint64().toString(), true);
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return { groupId: isSet(object.groupId) ? Long.fromValue(object.groupId) : Long.UZERO };
    },
    toJSON(message) {
        const obj = {};
        if (!message.groupId.equals(Long.UZERO)) {
            obj.groupId = (message.groupId || Long.UZERO).toString();
        }
        return obj;
    },
    create(base) {
        return EventCreateGroup.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseEventCreateGroup();
        message.groupId = (object.groupId !== undefined && object.groupId !== null)
            ? Long.fromValue(object.groupId)
            : Long.UZERO;
        return message;
    },
};
function createBaseEventUpdateGroup() {
    return { groupId: Long.UZERO };
}
export const EventUpdateGroup = {
    encode(message, writer = new BinaryWriter()) {
        if (!message.groupId.equals(Long.UZERO)) {
            writer.uint32(8).uint64(message.groupId.toString());
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseEventUpdateGroup();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.groupId = Long.fromString(reader.uint64().toString(), true);
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return { groupId: isSet(object.groupId) ? Long.fromValue(object.groupId) : Long.UZERO };
    },
    toJSON(message) {
        const obj = {};
        if (!message.groupId.equals(Long.UZERO)) {
            obj.groupId = (message.groupId || Long.UZERO).toString();
        }
        return obj;
    },
    create(base) {
        return EventUpdateGroup.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseEventUpdateGroup();
        message.groupId = (object.groupId !== undefined && object.groupId !== null)
            ? Long.fromValue(object.groupId)
            : Long.UZERO;
        return message;
    },
};
function createBaseEventCreateGroupPolicy() {
    return { address: "" };
}
export const EventCreateGroupPolicy = {
    encode(message, writer = new BinaryWriter()) {
        if (message.address !== "") {
            writer.uint32(10).string(message.address);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseEventCreateGroupPolicy();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.address = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return { address: isSet(object.address) ? globalThis.String(object.address) : "" };
    },
    toJSON(message) {
        const obj = {};
        if (message.address !== "") {
            obj.address = message.address;
        }
        return obj;
    },
    create(base) {
        return EventCreateGroupPolicy.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseEventCreateGroupPolicy();
        message.address = object.address ?? "";
        return message;
    },
};
function createBaseEventUpdateGroupPolicy() {
    return { address: "" };
}
export const EventUpdateGroupPolicy = {
    encode(message, writer = new BinaryWriter()) {
        if (message.address !== "") {
            writer.uint32(10).string(message.address);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseEventUpdateGroupPolicy();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.address = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return { address: isSet(object.address) ? globalThis.String(object.address) : "" };
    },
    toJSON(message) {
        const obj = {};
        if (message.address !== "") {
            obj.address = message.address;
        }
        return obj;
    },
    create(base) {
        return EventUpdateGroupPolicy.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseEventUpdateGroupPolicy();
        message.address = object.address ?? "";
        return message;
    },
};
function createBaseEventSubmitProposal() {
    return { proposalId: Long.UZERO };
}
export const EventSubmitProposal = {
    encode(message, writer = new BinaryWriter()) {
        if (!message.proposalId.equals(Long.UZERO)) {
            writer.uint32(8).uint64(message.proposalId.toString());
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseEventSubmitProposal();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.proposalId = Long.fromString(reader.uint64().toString(), true);
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return { proposalId: isSet(object.proposalId) ? Long.fromValue(object.proposalId) : Long.UZERO };
    },
    toJSON(message) {
        const obj = {};
        if (!message.proposalId.equals(Long.UZERO)) {
            obj.proposalId = (message.proposalId || Long.UZERO).toString();
        }
        return obj;
    },
    create(base) {
        return EventSubmitProposal.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseEventSubmitProposal();
        message.proposalId = (object.proposalId !== undefined && object.proposalId !== null)
            ? Long.fromValue(object.proposalId)
            : Long.UZERO;
        return message;
    },
};
function createBaseEventWithdrawProposal() {
    return { proposalId: Long.UZERO };
}
export const EventWithdrawProposal = {
    encode(message, writer = new BinaryWriter()) {
        if (!message.proposalId.equals(Long.UZERO)) {
            writer.uint32(8).uint64(message.proposalId.toString());
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseEventWithdrawProposal();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.proposalId = Long.fromString(reader.uint64().toString(), true);
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return { proposalId: isSet(object.proposalId) ? Long.fromValue(object.proposalId) : Long.UZERO };
    },
    toJSON(message) {
        const obj = {};
        if (!message.proposalId.equals(Long.UZERO)) {
            obj.proposalId = (message.proposalId || Long.UZERO).toString();
        }
        return obj;
    },
    create(base) {
        return EventWithdrawProposal.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseEventWithdrawProposal();
        message.proposalId = (object.proposalId !== undefined && object.proposalId !== null)
            ? Long.fromValue(object.proposalId)
            : Long.UZERO;
        return message;
    },
};
function createBaseEventVote() {
    return { proposalId: Long.UZERO };
}
export const EventVote = {
    encode(message, writer = new BinaryWriter()) {
        if (!message.proposalId.equals(Long.UZERO)) {
            writer.uint32(8).uint64(message.proposalId.toString());
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseEventVote();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.proposalId = Long.fromString(reader.uint64().toString(), true);
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return { proposalId: isSet(object.proposalId) ? Long.fromValue(object.proposalId) : Long.UZERO };
    },
    toJSON(message) {
        const obj = {};
        if (!message.proposalId.equals(Long.UZERO)) {
            obj.proposalId = (message.proposalId || Long.UZERO).toString();
        }
        return obj;
    },
    create(base) {
        return EventVote.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseEventVote();
        message.proposalId = (object.proposalId !== undefined && object.proposalId !== null)
            ? Long.fromValue(object.proposalId)
            : Long.UZERO;
        return message;
    },
};
function createBaseEventExec() {
    return { proposalId: Long.UZERO, result: 0, logs: "" };
}
export const EventExec = {
    encode(message, writer = new BinaryWriter()) {
        if (!message.proposalId.equals(Long.UZERO)) {
            writer.uint32(8).uint64(message.proposalId.toString());
        }
        if (message.result !== 0) {
            writer.uint32(16).int32(message.result);
        }
        if (message.logs !== "") {
            writer.uint32(26).string(message.logs);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseEventExec();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.proposalId = Long.fromString(reader.uint64().toString(), true);
                    continue;
                }
                case 2: {
                    if (tag !== 16) {
                        break;
                    }
                    message.result = reader.int32();
                    continue;
                }
                case 3: {
                    if (tag !== 26) {
                        break;
                    }
                    message.logs = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            proposalId: isSet(object.proposalId) ? Long.fromValue(object.proposalId) : Long.UZERO,
            result: isSet(object.result) ? proposalExecutorResultFromJSON(object.result) : 0,
            logs: isSet(object.logs) ? globalThis.String(object.logs) : "",
        };
    },
    toJSON(message) {
        const obj = {};
        if (!message.proposalId.equals(Long.UZERO)) {
            obj.proposalId = (message.proposalId || Long.UZERO).toString();
        }
        if (message.result !== 0) {
            obj.result = proposalExecutorResultToJSON(message.result);
        }
        if (message.logs !== "") {
            obj.logs = message.logs;
        }
        return obj;
    },
    create(base) {
        return EventExec.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseEventExec();
        message.proposalId = (object.proposalId !== undefined && object.proposalId !== null)
            ? Long.fromValue(object.proposalId)
            : Long.UZERO;
        message.result = object.result ?? 0;
        message.logs = object.logs ?? "";
        return message;
    },
};
function createBaseEventLeaveGroup() {
    return { groupId: Long.UZERO, address: "" };
}
export const EventLeaveGroup = {
    encode(message, writer = new BinaryWriter()) {
        if (!message.groupId.equals(Long.UZERO)) {
            writer.uint32(8).uint64(message.groupId.toString());
        }
        if (message.address !== "") {
            writer.uint32(18).string(message.address);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseEventLeaveGroup();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.groupId = Long.fromString(reader.uint64().toString(), true);
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.address = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            groupId: isSet(object.groupId) ? Long.fromValue(object.groupId) : Long.UZERO,
            address: isSet(object.address) ? globalThis.String(object.address) : "",
        };
    },
    toJSON(message) {
        const obj = {};
        if (!message.groupId.equals(Long.UZERO)) {
            obj.groupId = (message.groupId || Long.UZERO).toString();
        }
        if (message.address !== "") {
            obj.address = message.address;
        }
        return obj;
    },
    create(base) {
        return EventLeaveGroup.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseEventLeaveGroup();
        message.groupId = (object.groupId !== undefined && object.groupId !== null)
            ? Long.fromValue(object.groupId)
            : Long.UZERO;
        message.address = object.address ?? "";
        return message;
    },
};
function createBaseEventProposalPruned() {
    return { proposalId: Long.UZERO, status: 0, tallyResult: undefined };
}
export const EventProposalPruned = {
    encode(message, writer = new BinaryWriter()) {
        if (!message.proposalId.equals(Long.UZERO)) {
            writer.uint32(8).uint64(message.proposalId.toString());
        }
        if (message.status !== 0) {
            writer.uint32(16).int32(message.status);
        }
        if (message.tallyResult !== undefined) {
            TallyResult.encode(message.tallyResult, writer.uint32(26).fork()).join();
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseEventProposalPruned();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.proposalId = Long.fromString(reader.uint64().toString(), true);
                    continue;
                }
                case 2: {
                    if (tag !== 16) {
                        break;
                    }
                    message.status = reader.int32();
                    continue;
                }
                case 3: {
                    if (tag !== 26) {
                        break;
                    }
                    message.tallyResult = TallyResult.decode(reader, reader.uint32());
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            proposalId: isSet(object.proposalId) ? Long.fromValue(object.proposalId) : Long.UZERO,
            status: isSet(object.status) ? proposalStatusFromJSON(object.status) : 0,
            tallyResult: isSet(object.tallyResult) ? TallyResult.fromJSON(object.tallyResult) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (!message.proposalId.equals(Long.UZERO)) {
            obj.proposalId = (message.proposalId || Long.UZERO).toString();
        }
        if (message.status !== 0) {
            obj.status = proposalStatusToJSON(message.status);
        }
        if (message.tallyResult !== undefined) {
            obj.tallyResult = TallyResult.toJSON(message.tallyResult);
        }
        return obj;
    },
    create(base) {
        return EventProposalPruned.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseEventProposalPruned();
        message.proposalId = (object.proposalId !== undefined && object.proposalId !== null)
            ? Long.fromValue(object.proposalId)
            : Long.UZERO;
        message.status = object.status ?? 0;
        message.tallyResult = (object.tallyResult !== undefined && object.tallyResult !== null)
            ? TallyResult.fromPartial(object.tallyResult)
            : undefined;
        return message;
    },
};
function createBaseEventTallyError() {
    return { proposalId: Long.UZERO, errorMessage: "" };
}
export const EventTallyError = {
    encode(message, writer = new BinaryWriter()) {
        if (!message.proposalId.equals(Long.UZERO)) {
            writer.uint32(8).uint64(message.proposalId.toString());
        }
        if (message.errorMessage !== "") {
            writer.uint32(18).string(message.errorMessage);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseEventTallyError();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.proposalId = Long.fromString(reader.uint64().toString(), true);
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.errorMessage = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            proposalId: isSet(object.proposalId) ? Long.fromValue(object.proposalId) : Long.UZERO,
            errorMessage: isSet(object.errorMessage) ? globalThis.String(object.errorMessage) : "",
        };
    },
    toJSON(message) {
        const obj = {};
        if (!message.proposalId.equals(Long.UZERO)) {
            obj.proposalId = (message.proposalId || Long.UZERO).toString();
        }
        if (message.errorMessage !== "") {
            obj.errorMessage = message.errorMessage;
        }
        return obj;
    },
    create(base) {
        return EventTallyError.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseEventTallyError();
        message.proposalId = (object.proposalId !== undefined && object.proposalId !== null)
            ? Long.fromValue(object.proposalId)
            : Long.UZERO;
        message.errorMessage = object.errorMessage ?? "";
        return message;
    },
};
function isSet(value) {
    return value !== null && value !== undefined;
}
