// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               unknown
// source: tendermint/version/types.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import Long from "long";
export const protobufPackage = "tendermint.version";
function createBaseApp() {
    return { protocol: Long.UZERO, software: "" };
}
export const App = {
    encode(message, writer = new BinaryWriter()) {
        if (!message.protocol.equals(Long.UZERO)) {
            writer.uint32(8).uint64(message.protocol.toString());
        }
        if (message.software !== "") {
            writer.uint32(18).string(message.software);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseApp();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.protocol = Long.fromString(reader.uint64().toString(), true);
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.software = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            protocol: isSet(object.protocol) ? Long.fromValue(object.protocol) : Long.UZERO,
            software: isSet(object.software) ? globalThis.String(object.software) : "",
        };
    },
    toJSON(message) {
        const obj = {};
        if (!message.protocol.equals(Long.UZERO)) {
            obj.protocol = (message.protocol || Long.UZERO).toString();
        }
        if (message.software !== "") {
            obj.software = message.software;
        }
        return obj;
    },
    create(base) {
        return App.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseApp();
        message.protocol = (object.protocol !== undefined && object.protocol !== null)
            ? Long.fromValue(object.protocol)
            : Long.UZERO;
        message.software = object.software ?? "";
        return message;
    },
};
function createBaseConsensus() {
    return { block: Long.UZERO, app: Long.UZERO };
}
export const Consensus = {
    encode(message, writer = new BinaryWriter()) {
        if (!message.block.equals(Long.UZERO)) {
            writer.uint32(8).uint64(message.block.toString());
        }
        if (!message.app.equals(Long.UZERO)) {
            writer.uint32(16).uint64(message.app.toString());
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseConsensus();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.block = Long.fromString(reader.uint64().toString(), true);
                    continue;
                }
                case 2: {
                    if (tag !== 16) {
                        break;
                    }
                    message.app = Long.fromString(reader.uint64().toString(), true);
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            block: isSet(object.block) ? Long.fromValue(object.block) : Long.UZERO,
            app: isSet(object.app) ? Long.fromValue(object.app) : Long.UZERO,
        };
    },
    toJSON(message) {
        const obj = {};
        if (!message.block.equals(Long.UZERO)) {
            obj.block = (message.block || Long.UZERO).toString();
        }
        if (!message.app.equals(Long.UZERO)) {
            obj.app = (message.app || Long.UZERO).toString();
        }
        return obj;
    },
    create(base) {
        return Consensus.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseConsensus();
        message.block = (object.block !== undefined && object.block !== null) ? Long.fromValue(object.block) : Long.UZERO;
        message.app = (object.app !== undefined && object.app !== null) ? Long.fromValue(object.app) : Long.UZERO;
        return message;
    },
};
function isSet(value) {
    return value !== null && value !== undefined;
}
